eth_sendTransaction returns internal trace on missing param
evmos/ethermint pull request #1284
Opened 2022-08-19 23:20 UTC by adisaran64

Closes: #1275 

## Description

changes the `eth_sendTransaction` request to provide a properly formatted error (instead of an internal stack trace) when missing input params (the `from` field)

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2022-08-20 01:21 UTC, facs95 requested changes
Thanks @adisaran64 ! This looks great. Please just remove those two lines and this should be ready to merge 👌

2022-08-20 01:21 UTC, facs95 commented on tests/rpc/rpc_test.go
> +	return
I think we should remove this two lines

2022-08-22 14:54 UTC, facs95 commented on tests/rpc/rpc_test.go
> +	return
Also we are trying to migrate our integrations tests to the new python test suite. You could add the test in the `test/integration_tests/test_types.py` file

2022-08-24 10:32 UTC, fedekunze approved these changes
utACK. Can you add a bug-fix changelog entry?

2022-08-25 11:22 UTC, facs95 approved these changes

2022-08-25 11:22 UTC, merged