fix: add authz ante handler
evmos/ethermint pull request #1741
Opened 2023-04-05 23:01 UTC by facs95

Closes: #XXX

## Description

Adds authz ante check with the corresponding tests. Starts the process of reorganizing tests based on the work done on Evmos.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2023-04-06 00:36 UTC, austinchandra requested changes

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz_test.go
> +						sdk.NewCoins(sdk.NewInt64Coin(evmtypes.DefaultEVMDenom, 100e6)),
```suggestion
						sdk.NewCoins(sdk.NewInt64Coin(evmtypes.DefaultEVMDenom, 1e8)),
```

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz_test.go
> +					sdk.NewCoins(sdk.NewInt64Coin(evmtypes.DefaultEVMDenom, 100e6)),
```suggestion
					sdk.NewCoins(sdk.NewInt64Coin(evmtypes.DefaultEVMDenom, 1e8)),
```

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz_test.go
> +				createNestedMsgExec(
Code is duplicated, can refactor to a util:

e.g. `createNestedExecMsgSend(depth int)`

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz_test.go
> +func createNestedMsgExec(a sdk.AccAddress, nestedLvl int, lastLvlMsgs []sdk.Msg) *authz.MsgExec {
```suggestion
func createNestedMsgExec(a sdk.AccAddress, numLevels int, msgsToExec []sdk.Msg) *authz.MsgExec {
```

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz_test.go
> +					testAddresses[0],
nit: can move `testAddresses` to file-global variables, then use them from the helper methods, to avoid passing them each time.

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz_test.go
> +func createTx(priv cryptotypes.PrivKey, msgs ...sdk.Msg) (sdk.Tx, error) {
Can we move this to `testutils`?

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz.go
> +			nestedLvl++
How is this `nestedLvl` supposed to work? Currently, it checks that:

`max_depth + max_msgs_on_single_layer < maxNestedMsgs`

Is this the intent?

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz_test.go
> +						banktypes.NewMsgSend(
Also duplicated (same as above).

2023-04-06 00:36 UTC, austinchandra commented on app/ante/authz_test.go
> +				coinAmount := sdk.NewCoin(evmtypes.DefaultEVMDenom, sdk.NewInt(20))
nit: refactor this to a local helper for code clarity

2023-04-06 00:36 UTC, austinchandra commented on app/ante/eip712.go
> +			sdk.MsgTypeURL(&evmtypes.MsgEthereumTx{}),
Prefer a global registry of disabled tx's to decrease the likelihood of updating one place but not the other.

2023-04-06 00:36 UTC, austinchandra commented on testutil/tx/eip712.go
> +// the arguments, using the legacy implementation as specified.
```suggestion
// the arguments.
```

2023-04-06 00:36 UTC, austinchandra commented on app/ante/utils_test.go
> +	header := suite.ctx.BlockHeader()
Why is this necessary?

2023-04-06 21:55 UTC, austinchandra approved these changes

2023-04-10 14:18 UTC, facs95 commented on app/ante/authz.go
> +const maxNestedMsgs = 6
Why the change to 6 ?

2023-04-10 16:00 UTC, merged